# Generated by Django 3.1.6 on 2025-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('objet', models.CharField(choices=[('info', 'Demande d’informations'), ('visite', 'Demande de visite'), ('admission', 'Demande d’admission'), ('autre', 'Autre')], max_length=20)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
