# Generated by Django 3.1.6 on 2025-05-03 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitalia_app', '0002_chambre_evenement_planningeventinfirmier_planningeventresident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planningeventinfirmier',
            options={'verbose_name': 'Événement de planning infirmier', 'verbose_name_plural': 'Événements de planning infirmier'},
        ),
        migrations.AlterField(
            model_name='planningeventinfirmier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='planningeventinfirmier',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
