# Generated by Django 3.1.6 on 2025-05-03 12:53

from django.db import migrations, models
import vitalia_app.models.Profil


class Migration(migrations.Migration):

    dependencies = [
        ('vitalia_app', '0002_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=vitalia_app.models.Profil.upload_to),
        ),
    ]
