# Generated by Django 3.1.6 on 2025-05-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitalia_app', '0003_auto_20250503_1620'),
        ('vitalia_app', '0002_dossiermedical'),
    ]

    operations = [
    ]
