# Generated by Django 4.2.20 on 2025-05-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitalia_app', '0002_dossiermedical'),
        ('vitalia_app', '0003_auto_20250503_1620'),
    ]

    operations = [
    ]
