# Generated by Django 3.1.6 on 2025-05-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitalia_app', '0005_alert_alerthistory_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chambre',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='connectedobject',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objets_connectes', to='vitalia_app.chambre'),
        ),
    ]
