# Generated by Django 3.1.6 on 2025-05-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitalia_app', '0006_auto_20250505_2324'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chambre',
            table='vitalia_app_chambre',
        ),
    ]
