# Generated by Django 3.1.6 on 2025-05-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitalia_app', '0007_auto_20250505_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('text_value', models.CharField(blank=True, max_length=100, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('connected_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='vitalia_app.connectedobject')),
            ],
        ),
    ]
