# Generated by Django 3.1.6 on 2025-05-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalia_app', '0007_auto_20250505_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedobject',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
